In [1]:
import numpy as np

In [2]:
array1 = np.array([[10, 8], [3, 5]])

In [6]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
disarray1 = np.linalg.inv(array1)
disarray1

array([[ 0.19230769, -0.30769231],
       [-0.11538462,  0.38461538]])

In [7]:
array1@disarray1

array([[1., 0.],
       [0., 1.]])

In [8]:
#2. 運用上列array計算特徵值、特徵向量?
eigenvalue, eigenvector = np.linalg.eig(array1)

In [9]:
#特徵值
eigenvalue

array([13.,  2.])

In [10]:
#特徵向量
eigenvector

array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])

In [11]:
#運用上列array計算SVD?
np.linalg.matrix_rank(array1)

2